### PR TITLE
Update crypto examples to match current beta1 behavior.

### PR DESCRIPTION
**Pull request by warner**
All the examples match, using actual samples of an assertion for
warner@mockmyid.com, using a local browserid checkout as an RP, plus the
real mockmyid.com pubkey. This should help folks test their
implementations.

### CODE REVIEW

**Comment by warner** [comment]
@callahad, see if this looks right.

**Comment by benadida** [comment]
high-level r+, I'm hoping @callahad will give it a detailed review :)

**Comment by callahad** [comment]
Will be able to do a detailed review of this tomorrow, once I get over the last few beta 1 hurdles.

**Comment by djc** [comment]
It would be nice if this could get merged, the current state of the beta1 branch spec is very confusing.

**Comment by callahad** [comment]
@djc I finally got a chance to review (I know, I'm a terrible person) -- this will get merged today :)

**Pull request merged**
